service: url-shortener
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  memorySize: 512
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    lambda: true

functions:
  api:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    slugsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        BillingMode: PROVISIONED
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Slugs
