service: url-shortener
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION}
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${env:AWS_REGION}:*:*'

resources:
  Resources:
    slugsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Slugs
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
          - AttributeName: url
            AttributeType: S
        BillingMode: PROVISIONED
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: url-index
            KeySchema:
              - AttributeName: url
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  api:
    memorySize: 512
    reservedConcurrency: 5
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
